import type { Metadata } from "next";
import { Onest } from "next/font/google";
import "./globals.css";
import localFont from "next/font/local";
import "./font.css";

const Novela = localFont({
  src: "./fonts/Novela-Regular.otf",
  variable: "--font-novela",
});

const OnestFont = Onest({
  variable: "--font-onest",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${OnestFont.className} ${Novela.className}  antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
